[biophysical_constants]
transcription_saturation_constant = 36                # units: µM -> changed to nM
characteristic_transcript_length = 1000                  # units: nt 
energy_promoter_state_1 = 28.82                           # units: kJ/mol, molar Gibbs energy for background expression
energy_promoter_state_2 = -20.38                          # units: kJ/mol, molar Gibbs energy for induced expression
inducer_dissociation_constant = 24190      # TODO: units: muM -> changed to nM, Adhikari et al. Table 2
inducer_cooperativity_parameter = 1.12    # TODO: units: dimensionless, Adhikari et al. Table 2
mRNA_half_life_in_min = 810           # TODO: units: min -> changed to s, Adhikari et al. Table 2
RNAPII_concentration = 67.5               # TODO: units: µM -> changed to nM, Adikari et al. Table 1
transcription_elongation_rate = 21      # TODO: units: nt/s, Adhikari et al. Table 1
transcription_time_constant = 0.61        # TODO: units: dimensionless, Adhikari et al. Table 2
gene_length_in_nt = 690                  # TODO: units: nt, Given in problem statement
